const {AppError}=require("../../lib/app-error");
const csvCell=value=>{const raw=value==null?"":String(value);const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`;};
class AttendanceService{
  constructor(repository){this.repository=repository;}
  paged(result,query){return {...result,page:query.page,pageSize:query.pageSize,totalPages:Math.ceil(result.total/query.pageSize)};}
  async myToday(org,user){const result=await this.repository.myToday(org,user);if(!result)throw new AppError(404,"EMPLOYEE_PROFILE_REQUIRED","Your login is not linked to an employee profile.");return result;}
  async punch(org,user,data,meta){const result=await this.repository.punch(org,user,data,meta);if(result?.error==="employee")throw new AppError(404,"EMPLOYEE_PROFILE_REQUIRED","Your login is not linked to an employee profile.");if(result?.error==="web_disabled")throw new AppError(403,"WEB_PUNCH_DISABLED","Web attendance punches are disabled by policy.");if(result?.error==="geolocation")throw new AppError(422,"GEOLOCATION_REQUIRED","Location is required for attendance punches.");if(result?.error==="shift")throw new AppError(422,"SHIFT_REQUIRED","No active shift is available for today.");if(result?.error==="action")throw new AppError(409,"INVALID_PUNCH_SEQUENCE",`This punch is not allowed. Next action: ${result.allowed.join(" or ")}.`);return result;}
  async daily(org,query){return this.paged(await this.repository.daily(org,query),query);}
  dailySummary(org,date){return this.repository.dailySummary(org,date);}
  async records(org,query){if(new Date(query.dateFrom)>new Date(query.dateTo))throw new AppError(422,"INVALID_DATE_RANGE","The end date must be on or after the start date.");return this.paged(await this.repository.records(org,query),query);}
  async record(org,id){const result=await this.repository.findRecord(org,id);if(!result)throw new AppError(404,"ATTENDANCE_NOT_FOUND","Attendance record not found.");return result;}
  async manual(org,data,user){if(data.clockInAt&&data.clockOutAt&&new Date(data.clockOutAt)<new Date(data.clockInAt))throw new AppError(422,"INVALID_PUNCH_TIMES","Clock-out must be after clock-in.");const result=await this.repository.manualRecord(org,data,user);if(result?.error==="employee")throw new AppError(422,"INVALID_EMPLOYEE","The employee does not belong to this organization.");if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT","This attendance record changed. Refresh and try again.");return result;}
  policy(org){return this.repository.policy(org);}
  async updatePolicy(org,data,user){const current=await this.repository.policy(org),half=data.halfDayMinutes??current.halfDayMinutes,full=data.fullDayMinutes??current.fullDayMinutes;if(half>=full)throw new AppError(422,"INVALID_ATTENDANCE_POLICY","Half-day minutes must be lower than full-day minutes.");const result=await this.repository.updatePolicy(org,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","The attendance policy changed. Refresh and try again.");return result;}
  async shifts(org,query){return this.paged(await this.repository.listShifts(org,query),query);}
  async shift(org,id){const result=await this.repository.findShift(org,id);if(!result)throw new AppError(404,"SHIFT_NOT_FOUND","Shift not found.");return result;}
  async createShift(org,data,user){try{return await this.repository.createShift(org,data,user);}catch(error){if(error.code==="23505")throw new AppError(409,"SHIFT_CONFLICT","A shift with this code or name already exists, or another default shift is configured.");throw error;}}
  async updateShift(org,id,data,user){try{const result=await this.repository.updateShift(org,id,data,user);if(!result){await this.shift(org,id);throw new AppError(409,"VERSION_CONFLICT","This shift changed. Refresh and try again.");}return result;}catch(error){if(error.code==="23505")throw new AppError(409,"SHIFT_CONFLICT","A shift with this code or name already exists.");throw error;}}
  async assignments(org,query){return this.paged(await this.repository.listAssignments(org,query),query);}
  async createAssignment(org,data,user){if(data.effectiveTo&&new Date(data.effectiveTo)<new Date(data.effectiveFrom))throw new AppError(422,"INVALID_DATE_RANGE","Assignment end date must follow its start date.");const result=await this.repository.createAssignment(org,data,user);return this.resolveAssignment(result);}
  async updateAssignment(org,id,data){const result=await this.repository.updateAssignment(org,id,data);return this.resolveAssignment(result);}
  resolveAssignment(result){if(result?.error==="reference")throw new AppError(422,"INVALID_SHIFT_ASSIGNMENT","The employee or shift is unavailable in this organization.");if(result?.error==="range")throw new AppError(422,"INVALID_DATE_RANGE","Assignment end date must follow its start date.");if(result?.error==="overlap")throw new AppError(409,"SHIFT_ASSIGNMENT_OVERLAP","This employee already has a shift assignment during those dates.");if(result?.error==="not_found")throw new AppError(404,"SHIFT_ASSIGNMENT_NOT_FOUND","Shift assignment not found.");if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT","This assignment changed. Refresh and try again.");return result;}
  metadata(org){return this.repository.metadata(org);}
  async createRegularization(org,user,data){if(data.requestedClockIn&&data.requestedClockOut&&new Date(data.requestedClockOut)<new Date(data.requestedClockIn))throw new AppError(422,"INVALID_PUNCH_TIMES","Requested clock-out must be after clock-in.");try{const result=await this.repository.createRegularization(org,user,data);if(result?.error==="employee")throw new AppError(404,"EMPLOYEE_PROFILE_REQUIRED","Your login is not linked to an employee profile.");if(result?.error==="disabled")throw new AppError(403,"REGULARIZATION_DISABLED","Attendance correction requests are disabled.");if(result?.error==="window")throw new AppError(422,"REGULARIZATION_WINDOW_CLOSED","The attendance date is outside the correction window.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"REGULARIZATION_PENDING","A pending correction request already exists for this date.");throw error;}}
  async regularizations(org,query,user=null){return this.paged(await this.repository.regularizations(org,query,user),query);}
  async review(org,id,data,user){const result=await this.repository.reviewRegularization(org,id,data,user);if(result?.error==="not_found")throw new AppError(404,"REGULARIZATION_NOT_FOUND","Correction request not found.");if(result?.error==="reviewed")throw new AppError(409,"REGULARIZATION_REVIEWED","This correction request has already been reviewed.");if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT","This request changed. Refresh and try again.");return result;}
  async cancel(org,user,id,version){const result=await this.repository.cancelRegularization(org,user,id,version);if(!result)throw new AppError(409,"REGULARIZATION_NOT_CANCELLABLE","The request was changed, reviewed, or does not belong to you.");return result;}
  history(org,id){return this.record(org,id).then(()=>this.repository.history(org,id));}
  async export(org,query){const items=[];let page=1,total=0;do{const result=await this.repository.records(org,{...query,page,pageSize:100});items.push(...result.items);total=result.total;page+=1;}while(items.length<total);const rows=[["Date","Employee Number","Employee","Department","Shift","Status","Clock In","Clock Out","Worked Minutes","Late Minutes","Overtime Minutes","Source"],...items.map(item=>[item.attendanceDate,item.employeeNumber,item.employeeName,item.departmentName,item.shiftName,item.status,item.clockInAt,item.clockOutAt,item.workedMinutes,item.lateMinutes,item.overtimeMinutes,item.source])];return rows.map(row=>row.map(csvCell).join(",")).join("\n");}
}
module.exports={AttendanceService};
