const {AppError}=require("../../lib/app-error");
const csvCell=value=>{const raw=value==null?"":String(value);const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`;};
const daysBetween=(from,to)=>Math.floor((new Date(`${to}T00:00:00Z`)-new Date(`${from}T00:00:00Z`))/86400000);

class WorklogsService{
  constructor(repository){this.repository=repository;}
  paged(result,query){return {...result,page:query.page,pageSize:query.pageSize,totalPages:Math.ceil(result.total/query.pageSize)};}
  assertRange(from,to,maxDays=120){if(new Date(from)>new Date(to))throw new AppError(422,"INVALID_DATE_RANGE","The end date must be on or after the start date.");if(daysBetween(from,to)>maxDays)throw new AppError(422,"DATE_RANGE_TOO_LARGE",`Select a range of ${maxDays} days or less.`);}
  metadata(org,user,search){return this.repository.metadata(org,user,search);}
  async clients(org,query){return this.paged(await this.repository.listClients(org,query),query);}
  async createClient(org,data,user){try{return await this.repository.createClient(org,data,user);}catch(error){if(error.code==="23505")throw new AppError(409,"WORK_CLIENT_CONFLICT","A work client with this code or name already exists.");throw error;}}
  async updateClient(org,id,data,user){try{const result=await this.repository.updateClient(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This client changed. Refresh and try again.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"WORK_CLIENT_CONFLICT","A work client with this code or name already exists.");throw error;}}
  async projects(org,query){return this.paged(await this.repository.listProjects(org,query),query);}
  async createProject(org,data,user){this.validateProjectDates(data);try{const result=await this.repository.createProject(org,data,user);if(result?.error==="client")throw new AppError(422,"INVALID_WORK_CLIENT","The selected work client is unavailable.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"WORK_PROJECT_CONFLICT","A project with this code or name already exists.");throw error;}}
  async updateProject(org,id,data,user){this.validateProjectDates(data);try{const result=await this.repository.updateProject(org,id,data,user);if(result?.error==="client")throw new AppError(422,"INVALID_WORK_CLIENT","The selected work client is unavailable.");if(!result)throw new AppError(409,"VERSION_CONFLICT","This project changed. Refresh and try again.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"WORK_PROJECT_CONFLICT","A project with this code or name already exists.");throw error;}}
  validateProjectDates(data){if(data.startDate&&data.endDate&&new Date(data.endDate)<new Date(data.startDate))throw new AppError(422,"INVALID_DATE_RANGE","Project end date must follow its start date.");}
  async assignments(org,query){return this.paged(await this.repository.listAssignments(org,query),query);}
  async createAssignment(org,data,user){if(data.effectiveTo&&new Date(data.effectiveTo)<new Date(data.effectiveFrom))throw new AppError(422,"INVALID_DATE_RANGE","Assignment end date must follow its start date.");try{const result=await this.repository.createAssignment(org,data,user);if(result?.error==="reference")throw new AppError(422,"INVALID_PROJECT_ASSIGNMENT","The selected employee or project is unavailable.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"PROJECT_ASSIGNMENT_CONFLICT","This project assignment already exists for the date.");throw error;}}
  async updateAssignment(org,id,data,user){const result=await this.repository.updateAssignment(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This assignment changed or no longer exists.");return result;}
  async myEntries(org,user,query){this.assertRange(query.dateFrom,query.dateTo);return this.paged(await this.repository.listEntries(org,query,user),query);}
  async entries(org,query){this.assertRange(query.dateFrom,query.dateTo);return this.paged(await this.repository.listEntries(org,query),query);}
  async createEntry(org,user,data){const result=await this.repository.createEntry(org,user,data);if(result?.error==="employee")throw new AppError(404,"EMPLOYEE_PROFILE_REQUIRED","Your login is not linked to an employee profile.");if(result?.error==="project")throw new AppError(422,"INVALID_WORK_PROJECT","The selected project is unavailable.");return result;}
  async updateEntry(org,user,id,data){const result=await this.repository.updateEntry(org,user,id,data);this.resolveEntry(result);return result;}
  async voidEntry(org,user,id,data){const result=await this.repository.voidEntry(org,user,id,data);this.resolveEntry(result);return result;}
  resolveEntry(result){if(result?.error==="not_found")throw new AppError(404,"WORK_LOG_NOT_FOUND","Work log entry not found.");if(result?.error==="locked")throw new AppError(409,"WORK_LOG_LOCKED","Submitted or approved work logs cannot be edited.");if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT","This work log changed. Refresh and try again.");if(result?.error==="project")throw new AppError(422,"INVALID_WORK_PROJECT","The selected project is unavailable.");}
  async submit(org,user,data){this.assertRange(data.periodStart,data.periodEnd,31);try{const result=await this.repository.submitTimesheet(org,user,data);if(result?.error==="employee")throw new AppError(404,"EMPLOYEE_PROFILE_REQUIRED","Your login is not linked to an employee profile.");if(result?.error==="empty")throw new AppError(422,"EMPTY_TIMESHEET","No editable work logs were found in this period.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"TIMESHEET_PERIOD_LOCKED","This period already has a submitted or approved timesheet.");throw error;}}
  async myTimesheets(org,user,query){this.assertRange(query.dateFrom,query.dateTo,370);return this.paged(await this.repository.listTimesheets(org,query,user),query);}
  async timesheets(org,query){this.assertRange(query.dateFrom,query.dateTo,370);return this.paged(await this.repository.listTimesheets(org,query),query);}
  async timesheet(org,id){const result=await this.repository.findTimesheet(org,id);if(!result)throw new AppError(404,"TIMESHEET_NOT_FOUND","Timesheet not found.");return result;}
  async review(org,id,data,user){const result=await this.repository.reviewTimesheet(org,id,data,user);this.resolveTimesheet(result);return result;}
  async reopen(org,id,data,user){const result=await this.repository.reopenTimesheet(org,id,data,user);this.resolveTimesheet(result);return result;}
  resolveTimesheet(result){if(result?.error==="not_found")throw new AppError(404,"TIMESHEET_NOT_FOUND","Timesheet not found.");if(result?.error==="state")throw new AppError(409,"INVALID_TIMESHEET_STATE","This timesheet is not in a reviewable state.");if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT","This timesheet changed. Refresh and try again.");}
  async report(org,query){this.assertRange(query.dateFrom,query.dateTo,370);const result=await this.repository.report(org,query);return {items:result.items.map(item=>({...item,totalMinutes:Number(item.totalMinutes||0),billableMinutes:Number(item.billableMinutes||0),entryCount:Number(item.entryCount||0),employeeCount:Number(item.employeeCount||0)}))};}
  async export(org,query){this.assertRange(query.dateFrom,query.dateTo,370);const items=[];let page=1,total=0;do{const result=await this.repository.listEntries(org,{...query,page,pageSize:100});items.push(...result.items);total=result.total;if(total>50000)throw new AppError(422,"EXPORT_TOO_LARGE","Narrow the filters before exporting more than 50,000 rows.");page+=1;}while(items.length<total);const rows=[["Date","Employee Number","Employee","Client","Project","Task","Minutes","Billable","Status","Timesheet"],...items.map(item=>[item.workDate,item.employeeNumber,item.employeeName,item.clientName,item.projectName,item.taskTitle,item.minutes,item.isBillable?"Yes":"No",item.status,item.timesheetId])];return rows.map(row=>row.map(csvCell).join(",")).join("\n");}
}
module.exports={WorklogsService};
