import {apiClient} from "../../api/client";
export type Page<T>={items:T[];total:number;page:number;pageSize:number;totalPages:number};
export type JobOpening={id:string;code:string;title:string;departmentId:string|null;departmentName:string|null;jobTitleId:string|null;jobTitleName:string|null;workLocationId:string|null;workLocationName:string|null;hiringManagerEmployeeId:string|null;hiringManagerName:string|null;employmentType:string;workMode:string;openings:number;minExperienceYears:number;maxExperienceYears:number|null;salaryMin:number|null;salaryMax:number|null;currency:string;description:string|null;status:"draft"|"open"|"on_hold"|"closed"|"cancelled";openedAt:string|null;closedAt:string|null;version:number;applicationCount?:number};
export type Candidate={id:string;firstName:string;lastName:string;candidateName:string;email:string;phone:string|null;currentCompany:string|null;currentTitle:string|null;totalExperienceYears:number;currentSalary:number|null;expectedSalary:number|null;currency:string;noticePeriodDays:number|null;sourceId:string|null;sourceName:string|null;resumeUrl:string|null;portfolioUrl:string|null;tags:string[];status:"active"|"hired"|"rejected"|"archived";version:number;applicationCount?:number};
export type Application={id:string;jobOpeningId:string;jobCode:string;jobTitle:string;candidateId:string;candidateName:string;candidateEmail:string;stageId:string|null;stageName:string|null;stageOrder:number|null;status:"active"|"offer"|"hired"|"rejected"|"withdrawn"|"archived";rating:number|null;ownerEmployeeId:string|null;ownerName:string|null;appliedAt:string;rejectedReason:string|null;version:number;interviewCount?:number;offerStatus?:string|null};
export type Interview={id:string;applicationId:string;jobTitle:string;candidateName:string;interviewType:string;scheduledStart:string;scheduledEnd:string;location:string|null;meetingUrl:string|null;interviewers:Array<{employeeId?:string|null;name:string}>;status:"scheduled"|"completed"|"cancelled"|"no_show";score:number|null;feedback:string|null;version:number};
export type Offer={id:string;applicationId:string;jobTitle:string;candidateName:string;offeredTitle:string;offeredSalary:number;currency:string;joiningDate:string|null;expiresAt:string|null;status:"draft"|"pending_approval"|"approved"|"released"|"accepted"|"declined"|"withdrawn";approverComment:string|null;approvedByName:string|null;approvedAt:string|null;version:number};
export type RecruitmentFilters={dateFrom?:string;dateTo?:string;search?:string;status?:string;jobOpeningId?:string;candidateId?:string;stageId?:string;page?:number};
const download=async(params:RecruitmentFilters)=>{const response=await apiClient.get("/recruitment/applications/export",{params,responseType:"blob"});const url=URL.createObjectURL(response.data),link=document.createElement("a");link.href=url;link.download="recruitment-applications.csv";link.click();URL.revokeObjectURL(url);};
export const recruitmentApi={
  metadata:async(search="")=>(await apiClient.get("/recruitment/metadata",{params:{search}})).data.data as {departments:Array<{id:string;name:string}>;jobTitles:Array<{id:string;name:string}>;locations:Array<{id:string;name:string}>;employees:Array<{id:string;employeeNumber:string;name:string}>;sources:Array<{id:string;name:string;sourceType:string}>;stages:Array<{id:string;code:string;name:string;stageOrder:number;isTerminal:boolean}>;jobs:Array<{id:string;code:string;title:string}>;candidates:Array<{id:string;name:string;email:string}>},
  jobs:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/jobs",{params:{...params,pageSize:100}})).data.data as Page<JobOpening>,
  createJob:async(data:Record<string,unknown>)=>(await apiClient.post("/recruitment/jobs",data)).data.data as JobOpening,
  updateJob:async(id:string,data:Record<string,unknown>)=>(await apiClient.patch(`/recruitment/jobs/${id}`,data)).data.data as JobOpening,
  candidates:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/candidates",{params:{...params,pageSize:100}})).data.data as Page<Candidate>,
  createCandidate:async(data:Record<string,unknown>)=>(await apiClient.post("/recruitment/candidates",data)).data.data as Candidate,
  updateCandidate:async(id:string,data:Record<string,unknown>)=>(await apiClient.patch(`/recruitment/candidates/${id}`,data)).data.data as Candidate,
  applications:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/applications",{params:{...params,pageSize:100}})).data.data as Page<Application>,
  createApplication:async(data:Record<string,unknown>)=>(await apiClient.post("/recruitment/applications",data)).data.data as Application,
  updateApplication:async(id:string,data:Record<string,unknown>)=>(await apiClient.patch(`/recruitment/applications/${id}`,data)).data.data as Application,
  interviews:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/interviews",{params:{...params,pageSize:100}})).data.data as Page<Interview>,
  createInterview:async(data:Record<string,unknown>)=>(await apiClient.post("/recruitment/interviews",data)).data.data,
  updateInterview:async(id:string,data:Record<string,unknown>)=>(await apiClient.patch(`/recruitment/interviews/${id}`,data)).data.data,
  offers:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/offers",{params:{...params,pageSize:100}})).data.data as Page<Offer>,
  createOffer:async(data:Record<string,unknown>)=>(await apiClient.post("/recruitment/offers",data)).data.data,
  updateOffer:async(id:string,data:Record<string,unknown>)=>(await apiClient.patch(`/recruitment/offers/${id}`,data)).data.data,
  reviewOffer:async(id:string,data:{decision:"approved"|"withdrawn"|"released";comment:string|null;version:number})=>(await apiClient.post(`/recruitment/offers/${id}/review`,data)).data.data,
  report:async(params:RecruitmentFilters={})=>(await apiClient.get("/recruitment/applications/report",{params:{...params,pageSize:100}})).data.data as {items:Array<{jobOpeningId:string;jobTitle:string;stageName:string;status:string;applicationCount:number;offerCount:number;hiredCount:number}>},
  exportCsv:download
};
