import {useState,type FormEvent} from "react";
import {ArrowLeft,ArrowRight,CheckCircle,Eye,EyeSlash,LockKey,ShieldCheck,TrendUp,UsersThree} from "@phosphor-icons/react";
import {BrandMark} from "../components/BrandMark";
import {useAuth} from "../features/auth/AuthProvider";
import {authApi} from "../features/auth/auth.api";

export function LoginPage(){
  const {login}=useAuth();const [mode,setMode]=useState<"login"|"forgot"|"reset">("login");const [email,setEmail]=useState("admin@rigweda.com");const [password,setPassword]=useState("");const [token,setToken]=useState("");const [visible,setVisible]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const run=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");setMessage("");try{if(mode==="login")await login(email,password);else if(mode==="forgot"){const result=await authApi.forgotPassword(email);if(result.developmentResetToken){setToken(result.developmentResetToken);setMode("reset");setMessage("Development reset token received. Choose a new password.");}else setMessage(result.message);}else{await authApi.resetPassword(token,password);setMode("login");setPassword("");setMessage("Password reset. You can sign in now.");}}catch(reason){const response=(reason as {response?:{data?:{error?:{message?:string}}}}).response;setError(response?.data?.error?.message||"The request could not be completed.");}finally{setBusy(false);}};
  return <main className="login-page"><section className="login-story"><div className="login-brand"><BrandMark/><strong>Rigweda</strong></div><div className="story-copy"><span>PEOPLE, IN RHYTHM</span><h1>A calmer way to run your workplace.</h1><p>Bring people, time, and payroll into one thoughtful operating system.</p><div className="story-points"><div><i><UsersThree/></i><span><strong>One people view</strong><small>Clear context across every team.</small></span></div><div><i><TrendUp/></i><span><strong>Decisions with confidence</strong><small>Reliable data when it matters.</small></span></div><div><i><ShieldCheck/></i><span><strong>Secure by design</strong><small>Modern identity and session controls.</small></span></div></div></div><footer>Independent implementation · PostgreSQL powered</footer></section><section className="login-form-side"><form className="login-form" onSubmit={run}><div className="login-lock">{mode==="reset"?<CheckCircle/>:<LockKey/>}</div><span className="login-kicker">{mode==="login"?"WELCOME BACK":"ACCOUNT RECOVERY"}</span><h2>{mode==="login"?"Sign in to your workspace":mode==="forgot"?"Reset your password":"Choose a new password"}</h2><p>{mode==="login"?"Use your Rigweda account to continue.":mode==="forgot"?"Enter the email connected to your account.":"Use at least 12 characters with upper, lower, number, and symbol."}</p>{mode!=="reset"&&<label>Email address<input autoComplete="username" type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label>}{mode!=="forgot"&&<label>{mode==="login"?"Password":"New password"}<div className="password-field"><input autoComplete={mode==="login"?"current-password":"new-password"} type={visible?"text":"password"} required minLength={mode==="login"?8:12} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button type="button" onClick={()=>setVisible(value=>!value)}>{visible?<EyeSlash/>:<Eye/>}<span className="sr-only">{visible?"Hide":"Show"} password</span></button></div></label>}{mode==="login"&&<div className="login-options"><label><input type="checkbox"/>Remember this device</label><button type="button" onClick={()=>{setMode("forgot");setError("");setMessage("");}}>Forgot password?</button></div>}{error&&<div className="login-error" role="alert">{error}</div>}{message&&<div className="login-message">{message}</div>}<button className="login-submit" disabled={busy}>{busy?"Please wait…":<>{mode==="login"?"Sign in securely":mode==="forgot"?"Send reset instructions":"Set new password"}<ArrowRight/></>}</button>{mode!=="login"&&<button type="button" className="back-to-login" onClick={()=>{setMode("login");setError("");setMessage("");}}><ArrowLeft/>Back to sign in</button>}<small className="security-note"><ShieldCheck/>Protected by Argon2id and rotating sessions</small></form></section></main>;
}
