import {useEffect,useState,type FormEvent} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Buildings,CaretDown,CaretRight,ClockCounterClockwise,GitBranch,List,MagnifyingGlass,MapPin,Palette,PencilSimple,Plus,TreeStructure,UsersThree,X} from "@phosphor-icons/react";
import {useAuth} from "../features/auth/AuthProvider";
import {structureApi,type Department,type DepartmentNode,type JobTitle,type StructureEntity,type StructureHistory,type StructureKind,type WorkLocation} from "../features/structure/structure.api";

const messageFor=(error:unknown)=>(error as {response?:{data?:{error?:{message?:string}}}}).response?.data?.error?.message||"The organization structure could not be saved.";
const empty={code:"",name:"",description:"",status:"active",parentDepartmentId:"",headEmployeeId:"",costCenter:"",jobLevel:"",grade:"",careerTrack:"",locationType:"office",timezone:"Asia/Kolkata",email:"",phone:"",capacity:"",line1:"",city:"",state:"",postalCode:"",country:"IN"};
type FormState=typeof empty;
const valueFor=(item:StructureEntity|null):FormState=>item?{
  ...empty,code:item.code,name:item.name,description:item.description||"",status:item.status,
  parentDepartmentId:"parentDepartmentId" in item?item.parentDepartmentId||"":"",headEmployeeId:"headEmployeeId" in item?item.headEmployeeId||"":"",costCenter:"costCenter" in item?item.costCenter||"":"",
  jobLevel:"jobLevel" in item?item.jobLevel||"":"",grade:"grade" in item?item.grade||"":"",careerTrack:"careerTrack" in item?item.careerTrack||"":"",
  locationType:"locationType" in item?item.locationType:"office",timezone:"timezone" in item?item.timezone:"Asia/Kolkata",email:"email" in item?item.email||"":"",phone:"phone" in item?item.phone||"":"",capacity:"capacity" in item&&item.capacity!==null?String(item.capacity):"",
  line1:"address" in item?item.address.line1||"":"",city:"address" in item?item.address.city||"":"",state:"address" in item?item.address.state||"":"",postalCode:"address" in item?item.address.postalCode||"":"",country:"address" in item?item.address.country||"IN":"IN"
}:empty;
const labels:{[K in StructureKind]:string}={department:"Department",job_title:"Designation",work_location:"Work location"};

function Header({onTheme,onMenu}:{onTheme:()=>void;onMenu:()=>void}){return <header className="topbar"><button className="mobile-menu icon-button" onClick={onMenu}><List/><span className="sr-only">Open navigation</span></button><div className="topbar-copy"><span>People operations</span><strong>Organization structure</strong></div><div className="topbar-actions"><button className="theme-trigger" onClick={onTheme}><Palette/>Theme</button><div className="avatar">MK</div></div></header>}

function StructureEditor({kind,item,departments,heads,onClose}:{kind:StructureKind;item:StructureEntity|null;departments:Department[];heads:Array<{id:string;employeeNumber:string;name:string}>;onClose:()=>void}){
  const queryClient=useQueryClient();const [form,setForm]=useState(()=>valueFor(item));const [error,setError]=useState("");
  const set=(key:keyof FormState,value:string)=>setForm(current=>({...current,[key]:value}));
  const save=useMutation({mutationFn:()=>{const common={code:form.code,name:form.name,description:form.description||null,status:form.status};let data:Record<string,unknown>=common;if(kind==="department")data={...common,parentDepartmentId:form.parentDepartmentId||null,headEmployeeId:form.headEmployeeId||null,costCenter:form.costCenter||null};if(kind==="job_title")data={...common,jobLevel:form.jobLevel||null,grade:form.grade||null,careerTrack:form.careerTrack||null};if(kind==="work_location")data={...common,locationType:form.locationType,timezone:form.timezone,email:form.email||null,phone:form.phone||null,capacity:form.capacity===""?null:Number(form.capacity),address:{line1:form.line1||null,city:form.city||null,state:form.state||null,postalCode:form.postalCode||null,country:form.country}};return item?structureApi.update(kind,item.id,{...data,version:item.version}):structureApi.create(kind,data);},onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["structure"]}),queryClient.invalidateQueries({queryKey:["employee-metadata"]})]);onClose();},onError:error=>setError(messageFor(error))});
  const submit=(event:FormEvent)=>{event.preventDefault();setError("");save.mutate();};
  return <div className="editor-layer"><form className="structure-editor" onSubmit={submit}><header><div><span>ORGANIZATION STRUCTURE</span><h2>{item?`Edit ${labels[kind].toLowerCase()}`:`New ${labels[kind].toLowerCase()}`}</h2><p>{item?`${item.code} · Version ${item.version}`:"Create a reusable employee assignment."}</p></div><button type="button" className="icon-button" onClick={onClose}><X/><span className="sr-only">Close</span></button></header><div className="structure-editor-body"><div className="structure-form-grid"><label>Code<input required value={form.code} onChange={e=>set("code",e.target.value.toUpperCase())} placeholder="ENGINEERING"/></label><label>Name<input required minLength={2} value={form.name} onChange={e=>set("name",e.target.value)} placeholder={labels[kind]}/></label><label className="form-span-two">Description<textarea value={form.description} onChange={e=>set("description",e.target.value)}/></label>
    {kind==="department"&&<><label>Parent department<select value={form.parentDepartmentId} onChange={e=>set("parentDepartmentId",e.target.value)}><option value="">Top level</option>{departments.filter(value=>value.id!==item?.id).map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Department head<select value={form.headEmployeeId} onChange={e=>set("headEmployeeId",e.target.value)}><option value="">Not assigned</option>{heads.map(value=><option key={value.id} value={value.id}>{value.name} · {value.employeeNumber}</option>)}</select></label><label>Cost center<input value={form.costCenter} onChange={e=>set("costCenter",e.target.value)} placeholder="CC-100"/></label></>}
    {kind==="job_title"&&<><label>Job level<input value={form.jobLevel} onChange={e=>set("jobLevel",e.target.value)} placeholder="L3"/></label><label>Grade<input value={form.grade} onChange={e=>set("grade",e.target.value)} placeholder="G7"/></label><label>Career track<select value={form.careerTrack} onChange={e=>set("careerTrack",e.target.value)}><option value="">Not specified</option><option value="individual">Individual contributor</option><option value="management">Management</option><option value="executive">Executive</option><option value="support">Support</option></select></label></>}
    {kind==="work_location"&&<><label>Location type<select value={form.locationType} onChange={e=>set("locationType",e.target.value)}><option value="office">Office</option><option value="branch">Branch</option><option value="client_site">Client site</option><option value="remote">Remote</option><option value="other">Other</option></select></label><label>Timezone<input required value={form.timezone} onChange={e=>set("timezone",e.target.value)} placeholder="Asia/Kolkata"/></label><label>Capacity<input type="number" min="0" value={form.capacity} onChange={e=>set("capacity",e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></label><label>Phone<input value={form.phone} onChange={e=>set("phone",e.target.value)}/></label><h3 className="form-span-two">Address</h3><label className="form-span-two">Address line<input value={form.line1} onChange={e=>set("line1",e.target.value)}/></label><label>City<input value={form.city} onChange={e=>set("city",e.target.value)}/></label><label>State<input value={form.state} onChange={e=>set("state",e.target.value)}/></label><label>Postal code<input value={form.postalCode} onChange={e=>set("postalCode",e.target.value)}/></label><label>Country<input required maxLength={2} value={form.country} onChange={e=>set("country",e.target.value.toUpperCase())}/></label></>}
    <label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div></div><footer>{error&&<p className="form-error">{error}</p>}<button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={save.isPending}>{save.isPending?"Saving…":"Save"}</button></footer></form></div>;
}

const changedFields=(event:StructureHistory)=>{if(!event.before)return ["Initial record"];const ignored=new Set(["updatedAt","createdAt","version","employeeCount","childCount"]);return Object.keys(event.after).filter(key=>!ignored.has(key)&&JSON.stringify(event.before?.[key])!==JSON.stringify(event.after[key])).map(key=>key.replace(/([A-Z])/g," $1").toLowerCase());};
function HistoryPanel({kind,item,onClose}:{kind:StructureKind;item:StructureEntity;onClose:()=>void}){const query=useQuery({queryKey:["structure","history",kind,item.id],queryFn:()=>structureApi.history(kind,item.id)});return <div className="editor-layer"><section className="structure-history"><header><div><span>CHANGE HISTORY</span><h2>{item.name}</h2><p>Immutable audit trail for this {labels[kind].toLowerCase()}.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div>{query.isLoading?<p className="directory-message">Loading history…</p>:query.data?.length?<ol>{query.data.map((event:StructureHistory)=><li key={event.id}><i/><div><strong>{event.eventType.replace("_"," ")}</strong><span>{event.actorName||"System"} · {new Date(event.occurredAt).toLocaleString()}</span><small>{changedFields(event).join(", ")||"No field-level changes"}</small></div></li>)}</ol>:<p className="directory-message">No history has been recorded.</p>}</div></section></div>}

function DepartmentBranch({node,depth=0}:{node:DepartmentNode;depth?:number}){const [open,setOpen]=useState(true);return <div className="department-branch"><button style={{paddingLeft:16+depth*24}} onClick={()=>setOpen(value=>!value)}>{node.children.length?(open?<CaretDown/>:<CaretRight/>):<span className="tree-spacer"/>}<span><strong>{node.name}</strong><small>{node.code} · {node.employeeCount} employees</small></span><em className={`status-pill ${node.status}`}>{node.status}</em></button>{open&&node.children.map(child=><DepartmentBranch key={child.id} node={child} depth={depth+1}/>)}</div>}

export function StructurePage({onTheme,onMenu}:{onTheme:()=>void;onMenu:()=>void}){
  const {hasPermission}=useAuth();
  const canManage=hasPermission("structure.manage");
  const [kind,setKind]=useState<StructureKind>("department"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[treeMode,setTreeMode]=useState(false),[editing,setEditing]=useState<StructureEntity|null|undefined>(undefined),[history,setHistory]=useState<StructureEntity|null>(null);
  useEffect(()=>{setSearch("");setStatus("all");setTreeMode(false);},[kind]);
  const summary=useQuery({queryKey:["structure","summary"],queryFn:structureApi.summary});const metadata=useQuery({queryKey:["structure","metadata"],queryFn:structureApi.metadata});
  const departments=useQuery({queryKey:["structure","departments",search,status],queryFn:()=>structureApi.departments({search,status,pageSize:100})});
  const titles=useQuery({queryKey:["structure","titles",search,status],queryFn:()=>structureApi.jobTitles({search,status,pageSize:100})});
  const locations=useQuery({queryKey:["structure","locations",search,status],queryFn:()=>structureApi.workLocations({search,status,pageSize:100})});
  const tree=useQuery({queryKey:["structure","tree"],queryFn:structureApi.departmentTree,enabled:kind==="department"&&treeMode});
  const items:StructureEntity[]=kind==="department"?(departments.data?.items||[]):kind==="job_title"?(titles.data?.items||[]):(locations.data?.items||[]);
  const loading=kind==="department"?departments.isLoading:kind==="job_title"?titles.isLoading:locations.isLoading;
  return <main className="main-content"><Header onTheme={onTheme} onMenu={onMenu}/><div className="structure-wrap"><section className="page-heading"><div><span className="eyebrow dark"><TreeStructure/>ORGANIZATION DESIGN</span><h1>Structure and assignments</h1><p>Maintain departments, designations, locations, and the hierarchy employees use.</p></div>{canManage&&<button className="primary-button" onClick={()=>setEditing(null)}><Plus/>New {labels[kind].toLowerCase()}</button>}</section>
    <section className="structure-summary"><article><span><Buildings/></span><div><small>Departments</small><strong>{summary.data?.departments??0}</strong><em>{summary.data?.activeDepartments??0} active</em></div></article><article><span><UsersThree/></span><div><small>Designations</small><strong>{summary.data?.jobTitles??0}</strong><em>{summary.data?.activeJobTitles??0} active</em></div></article><article><span><MapPin/></span><div><small>Locations</small><strong>{summary.data?.locations??0}</strong><em>{summary.data?.activeLocations??0} active</em></div></article><article><span><GitBranch/></span><div><small>Unassigned</small><strong>{summary.data?.unassignedDepartments??0}</strong><em>without department</em></div></article></section>
    <section className="structure-workspace"><div className="structure-tabs"><button className={kind==="department"?"active":""} onClick={()=>setKind("department")}><Buildings/>Departments</button><button className={kind==="job_title"?"active":""} onClick={()=>setKind("job_title")}><UsersThree/>Designations</button><button className={kind==="work_location"?"active":""} onClick={()=>setKind("work_location")}><MapPin/>Work locations</button></div><header><div className="search-box"><MagnifyingGlass/><input aria-label="Search structure" value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${labels[kind].toLowerCase()}s`}/></div><select aria-label="Filter structure status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select>{kind==="department"&&<button className={`secondary-button ${treeMode?"selected":""}`} onClick={()=>setTreeMode(value=>!value)}><TreeStructure/>{treeMode?"List view":"Tree view"}</button>}</header>
      {treeMode&&kind==="department"?<div className="department-tree">{tree.isLoading?<p className="directory-message">Loading hierarchy…</p>:tree.data?.map(node=><DepartmentBranch node={node} key={node.id}/>)}</div>:loading?<p className="directory-message">Loading organization structure…</p>:items.length===0?<div className="structure-empty"><TreeStructure/><strong>No {labels[kind].toLowerCase()}s found</strong><p>Create one or change the filters.</p></div>:<div className="structure-table"><div className="structure-table-head"><span>Name</span><span>Assignment</span><span>People</span><span>Status</span><span>Actions</span></div>{items.map(item=><div className="structure-row" key={item.id}><span><i>{item.name.slice(0,2).toUpperCase()}</i><span><strong>{item.name}</strong><small>{item.code}</small></span></span><span>{"parentDepartmentName" in item?(item.parentDepartmentName||"Top level"):"jobLevel" in item?([item.jobLevel,item.grade].filter(Boolean).join(" · ")||"Level not set"):([item.address.city,item.timezone].filter(Boolean).join(" · "))}</span><span><strong>{item.employeeCount}</strong><small> employees</small></span><span><em className={`status-pill ${item.status}`}>{item.status}</em></span><span><button title="View history" onClick={()=>setHistory(item)}><ClockCounterClockwise/></button>{canManage&&<button title={`Edit ${item.name}`} onClick={()=>setEditing(item)}><PencilSimple/></button>}</span></div>)}</div>}
    </section></div>{editing!==undefined&&<StructureEditor kind={kind} item={editing} departments={departments.data?.items||[]} heads={metadata.data?.headCandidates||[]} onClose={()=>setEditing(undefined)}/>} {history&&<HistoryPanel kind={kind} item={history} onClose={()=>setHistory(null)}/>}</main>;
}
