const test=require("node:test");const assert=require("node:assert/strict");
const {AuthService}=require("../src/modules/auth/auth.service");
const user={id:"user-1",email:"admin@example.com",displayName:"Admin",status:"active",membershipStatus:"active",organizationId:"org-1",organizationName:"Acme",roleKey:"system_admin",passwordHash:"hash"};
const env={AUTH_MAX_FAILED_ATTEMPTS:5,AUTH_LOCK_MINUTES:15};
test("successful login creates a rotating session",async()=>{const calls=[];const repository={findByEmail:async()=>user,recordSuccess:async()=>{},createSession:async(data)=>{calls.push(data);return"session-1";},event:async()=>{}};const passwords={verify:async()=>true};const tokens={createRefreshToken:()=>"refresh",hashRefreshToken:()=>"hash-refresh",refreshExpiresAt:()=>new Date("2030-01-01"),createAccessToken:()=>"access"};const result=await new AuthService({repository,passwords,tokens,env}).login({email:user.email,password:"password"});assert.equal(result.accessToken,"access");assert.equal(calls[0].tokenHash,"hash-refresh");});
test("invalid passwords are generic and recorded",async()=>{let failures=0;const repository={findByEmail:async()=>user,recordFailure:async()=>{failures++;},event:async()=>{}};const service=new AuthService({repository,passwords:{verify:async()=>false},tokens:{},env});await assert.rejects(()=>service.login({email:user.email,password:"wrong"}),error=>error.code==="INVALID_CREDENTIALS");assert.equal(failures,1);});
test("locked accounts are rejected before password verification",async()=>{const repository={findByEmail:async()=>({...user,lockedUntil:new Date(Date.now()+60_000)}),event:async()=>{}};const service=new AuthService({repository,passwords:{verify:async()=>true},tokens:{},env});await assert.rejects(()=>service.login({email:user.email,password:"password"}),error=>error.code==="ACCOUNT_LOCKED"&&error.statusCode===423);});

test("password change preserves only the current session",async()=>{let update;const repository={findWithPasswordById:async()=>user,updatePassword:async(...args)=>{update=args;},event:async()=>{}};let verification=0;const passwords={verify:async()=>++verification===1,hash:async()=>"next-hash"};const service=new AuthService({repository,passwords,tokens:{},env});await service.changePassword(user.id,"session-1","current","New.Password1!");assert.deepEqual(update,[user.id,"next-hash","session-1"]);});

test("current sessions must be closed through sign out",async()=>{const service=new AuthService({repository:{},passwords:{},tokens:{},env});await assert.rejects(()=>service.revokeSession(user.id,"session-1","session-1"),error=>error.code==="CURRENT_SESSION"&&error.statusCode===422);});

test("unknown password-reset accounts do not disclose account existence",async()=>{const repository={findByEmail:async()=>null};const service=new AuthService({repository,passwords:{},tokens:{},env});assert.equal(await service.requestPasswordReset("unknown@example.com"),null);});
