const test=require("node:test");
const assert=require("node:assert/strict");
const {LeaveService}=require("../src/modules/leave/leave.service");

const repository=()=>({
  metadata:async()=>({types:[]}),mySummary:async()=>({pending:0}),balancesForUser:async()=>[],listRequests:async()=>({items:[],total:101}),findRequest:async()=>({id:"request"}),createRequest:async()=>({id:"request"}),reviewRequest:async()=>({id:"request"}),cancelRequest:async()=>({id:"request"}),reviewCancellation:async()=>({id:"request"}),listTypes:async()=>({items:[],total:0}),findType:async()=>({id:"type"}),createType:async()=>({id:"type"}),updateType:async()=>({id:"type"}),listBalances:async()=>({items:[],total:0}),adjustBalance:async()=>({available:10}),listCalendars:async()=>({items:[],total:0}),createCalendar:async()=>({id:"calendar"}),updateCalendar:async()=>({id:"calendar"}),listHolidays:async()=>({items:[],total:0}),createHoliday:async()=>({id:"holiday"}),updateHoliday:async()=>({id:"holiday"}),teamCalendar:async()=>[],reportSummary:async()=>({requests:0})
});

test("leave request listings return stable pagination",async()=>{const result=await new LeaveService(repository()).requests("org",{page:2,pageSize:50,status:"all"});assert.equal(result.totalPages,3);});
test("leave requests reject reversed date ranges",async()=>{await assert.rejects(()=>new LeaveService(repository()).createRequest("org","user",{startDate:"2026-08-08",endDate:"2026-08-07",startSession:"full_day",endSession:"full_day"}),error=>error.code==="INVALID_DATE_RANGE");});
test("single-day requests reject conflicting half-day sessions",async()=>{await assert.rejects(()=>new LeaveService(repository()).createRequest("org","user",{startDate:"2026-08-08",endDate:"2026-08-08",startSession:"first_half",endSession:"second_half"}),error=>error.code==="INVALID_LEAVE_SESSION");});
test("overlapping requests become a conflict",async()=>{const repo=repository();repo.createRequest=async()=>({error:"overlap"});await assert.rejects(()=>new LeaveService(repo).createRequest("org","user",{startDate:"2026-08-08",endDate:"2026-08-08",startSession:"full_day",endSession:"full_day"}),error=>error.code==="LEAVE_REQUEST_OVERLAP"&&error.statusCode===409);});
test("insufficient balances return a useful validation error",async()=>{const repo=repository();repo.createRequest=async()=>({error:"balance",available:1,required:3,year:2026});await assert.rejects(()=>new LeaveService(repo).createRequest("org","user",{startDate:"2026-08-08",endDate:"2026-08-10",startSession:"full_day",endSession:"full_day"}),error=>error.code==="INSUFFICIENT_LEAVE_BALANCE"&&error.statusCode===422);});
test("team calendars reject ranges that are too large for synchronous reads",async()=>{await assert.rejects(()=>new LeaveService(repository()).teamCalendar("org",{dateFrom:"2026-01-01",dateTo:"2026-12-31"}),error=>error.code==="DATE_RANGE_TOO_LARGE");});
test("CSV export neutralizes spreadsheet formulas",async()=>{const repo=repository();repo.listRequests=async()=>({items:[{employeeNumber:"=2+2",employeeName:"Admin",requestedDays:1}],total:1});const csv=await new LeaveService(repo).export("org",{dateFrom:"2026-01-01",dateTo:"2026-12-31",status:"all"});assert.match(csv,/"'=2\+2"/);});
