const {AppError}=require("../../lib/app-error");
const csvCell=value=>{const raw=value==null?"":String(value);const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`;};
const daysBetween=(from,to)=>Math.floor((new Date(`${to}T00:00:00Z`)-new Date(`${from}T00:00:00Z`))/86400000);
class RecruitmentService{
  constructor(repository){this.repository=repository;}
  paged(result,query){return {...result,page:query.page,pageSize:query.pageSize,totalPages:Math.ceil(result.total/query.pageSize)};}
  assertRange(query,max=740){if(query.dateFrom&&query.dateTo){if(new Date(query.dateFrom)>new Date(query.dateTo))throw new AppError(422,"INVALID_DATE_RANGE","The end date must be on or after the start date.");if(daysBetween(query.dateFrom,query.dateTo)>max)throw new AppError(422,"DATE_RANGE_TOO_LARGE",`Select a range of ${max} days or less.`);}}
  metadata(org,search){return this.repository.metadata(org,search);}
  jobs(org,query){return this.repository.listJobs(org,query).then(result=>this.paged(result,query));}
  async createJob(org,data,user){this.assertJob(data);try{return await this.repository.createJob(org,data,user);}catch(error){if(error.code==="23505")throw new AppError(409,"JOB_OPENING_CONFLICT","A job opening with this code already exists.");throw error;}}
  async updateJob(org,id,data,user){this.assertJob(data);try{const result=await this.repository.updateJob(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This job opening changed. Refresh and try again.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"JOB_OPENING_CONFLICT","A job opening with this code already exists.");throw error;}}
  assertJob(data){if(data.salaryMin&&data.salaryMax&&Number(data.salaryMax)<Number(data.salaryMin))throw new AppError(422,"INVALID_SALARY_RANGE","Maximum salary must be greater than or equal to minimum salary.");if(data.maxExperienceYears&&Number(data.maxExperienceYears)<Number(data.minExperienceYears||0))throw new AppError(422,"INVALID_EXPERIENCE_RANGE","Maximum experience must be greater than or equal to minimum experience.");}
  candidates(org,query){return this.repository.listCandidates(org,query).then(result=>this.paged(result,query));}
  async createCandidate(org,data,user){try{return await this.repository.createCandidate(org,data,user);}catch(error){if(error.code==="23505")throw new AppError(409,"CANDIDATE_CONFLICT","A candidate with this email already exists.");throw error;}}
  async updateCandidate(org,id,data,user){try{const result=await this.repository.updateCandidate(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This candidate changed. Refresh and try again.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"CANDIDATE_CONFLICT","A candidate with this email already exists.");throw error;}}
  applications(org,query){this.assertRange(query);return this.repository.listApplications(org,query).then(result=>this.paged(result,query));}
  async createApplication(org,data,user){try{const result=await this.repository.createApplication(org,data,user);if(result?.error==="reference")throw new AppError(422,"INVALID_APPLICATION_REFERENCE","The selected job or candidate is unavailable.");return result;}catch(error){if(error.code==="23505")throw new AppError(409,"APPLICATION_CONFLICT","This candidate is already attached to the selected job.");throw error;}}
  async updateApplication(org,id,data,user){const result=await this.repository.updateApplication(org,id,data,user);this.resolve(result,"Application");return result;}
  interviews(org,query){this.assertRange(query);return this.repository.listInterviews(org,query).then(result=>this.paged(result,query));}
  async createInterview(org,data,user){this.assertInterview(data);const result=await this.repository.createInterview(org,data,user);if(result?.error==="application")throw new AppError(422,"INVALID_APPLICATION","The selected application is unavailable.");return result;}
  async updateInterview(org,id,data,user){this.assertInterview(data);const result=await this.repository.updateInterview(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This interview changed. Refresh and try again.");return result;}
  assertInterview(data){if(data.scheduledStart&&data.scheduledEnd&&new Date(data.scheduledEnd)<=new Date(data.scheduledStart))throw new AppError(422,"INVALID_INTERVIEW_TIME","Interview end time must be after start time.");}
  offers(org,query){return this.repository.listOffers(org,query).then(result=>this.paged(result,query));}
  async createOffer(org,data,user){const result=await this.repository.createOffer(org,data,user);if(result?.error==="application")throw new AppError(422,"INVALID_APPLICATION","The selected application is unavailable.");return result;}
  async updateOffer(org,id,data,user){const result=await this.repository.updateOffer(org,id,data,user);if(!result)throw new AppError(409,"VERSION_CONFLICT","This offer changed. Refresh and try again.");return result;}
  async reviewOffer(org,id,data,user){const result=await this.repository.reviewOffer(org,id,data,user);if(!result)throw new AppError(409,"OFFER_NOT_REVIEWABLE","This offer changed or is not reviewable.");return result;}
  report(org,query){this.assertRange(query);return this.repository.report(org,query);}
  async export(org,query){this.assertRange(query);const items=[];let page=1,total=0;do{const result=await this.repository.listApplications(org,{...query,page,pageSize:100});items.push(...result.items);total=result.total;if(total>50000)throw new AppError(422,"EXPORT_TOO_LARGE","Narrow the recruitment export below 50,000 rows.");page+=1;}while(items.length<total);const rows=[["Job Code","Job Title","Candidate","Email","Stage","Status","Rating","Owner","Applied At","Offer Status"],...items.map(item=>[item.jobCode,item.jobTitle,item.candidateName,item.candidateEmail,item.stageName,item.status,item.rating,item.ownerName,item.appliedAt,item.offerStatus])];return rows.map(row=>row.map(csvCell).join(",")).join("\n");}
  resolve(result,name){if(result?.error==="not_found")throw new AppError(404,`${name.toUpperCase()}_NOT_FOUND`,`${name} not found.`);if(result?.error==="version")throw new AppError(409,"VERSION_CONFLICT",`This ${name.toLowerCase()} changed. Refresh and try again.`);}
}
module.exports={RecruitmentService};
